# Generated by Django 6.0 on 2025-12-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_item_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='discription',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
