# Generated by Django 6.0 on 2025-12-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_categories_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='discription',
            field=models.TextField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
